Citizen.CreateThread(function()
    SetDiscordAppId('821531231907741697')
    SetDiscordRichPresenceAsset('logo')
    -- SetDiscordRichPresenceAssetSmall('lua')
    SetDiscordRichPresenceAssetText("adns-tech.fr")
    SetRichPresence("FiveM Store".." - ["..GetPlayerServerId(PlayerId()).. "]")
    SetDiscordRichPresenceAction(0, "Discord", "https://discord.gg/KJcCmA4tCh")
    SetDiscordRichPresenceAction(1, "Website", "https://adns-tech.fr")
end)